### PR TITLE
navbar revision

### PR DESCRIPTION
**Pull request by Odrunia-Mark-Ryan**
- revise navbar navigations

### CODE REVIEW

**Review by Galope-Jhean — CHANGES_REQUESTED** [review]
very niceeee

just try to place svgs into its seperate  file and call it inside the template

thanks <3

**Comment by Odrunia-Mark-Ryan** [comment]
understood, will do it asap

**Comment by Odrunia-Mark-Ryan** [comment]
on latest push, I fix navbar responsiveness in mobile screens

**Review by Galope-Jhean — APPROVED** [review]
great job

Note: decided not to create SVGs in their own separate files, as importing them through an image tag does not include its animation.

**Pull request merged**
