### PR TITLE
Wishlist page , Add-listing page, Terms & Conditions page,navrbar,footer, homepage,property page-mobile responsive

### PR DESCRIPTION
**Pull request by Odrunia-Mark-Ryan**
added proper list for cities, budget, bedroom count, make wishlist component and base structure, Terms and Conditions page, fix designs in navbar and footer, make add-listing page, mobile responsive of property page

### CODE REVIEW

**Comment by go-christianharrel** [comment]
For the next pull requests, please consider on the instructions discussed [here](https://github.com/PUP-BSIT/project-vrzn_appdev/discussions/18). Great Job @Odrunia-Mark-Ryan!

**Review by Galope-Jhean — CHANGES_REQUESTED** [review]
please see these as reference

https://github.com/PUP-BSIT/project-vrzn_appdev/discussions/17

https://github.com/PUP-BSIT/project-vrzn_appdev/issues/20

thanks

**Comment by Odrunia-Mark-Ryan** [comment]
added my changes, please check the components, thank you

**Comment by Galope-Jhean** [comment]
this will do for now, let's just clean this up moving forward

**Review by Galope-Jhean — APPROVED** [review]

**Pull request merged**
